[package]
name = "cardano-devkit"
version = "0.0.1"
edition = "2021"

[dependencies]
clap = { version = "4.5.16", features = ["derive", "string"] }
lazy_static = "1.5.0"

[dev-dependencies]
assert_cmd = "2.0.16"
predicates = "3.1.2"